server:
  address: "0.0.0.0"
  port: 1250
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        fromat_sql: true